export let usuarios = [
  {
    nombre: "Jaime Zapata Valencia",
    correo: "correo@correo.com",
    contrasena: "1234567",
    profesion: "Developer",
    usuario: "admin",
  },
  {
    nombre: "Mariana Reestrepo",
    correo: "correo@correo.com",
    contrasena: "1234567",
    profesion: "UX/UI",
    usuario: "mariana",
  },
];

export const recetasVegetarianas = [
  {
    id: 1,
    nombre: "Ensalada de Quinoa",
    descripcion: "Ensalada fresca con quinoa y vegetales.",
    pasos: ["Lava la quinoa", "Cocínala", "Mezcla con vegetales y aderezo"],
    dificultad: "Fácil",
    ingredientes: [
      "quinoa",
      "tomate",
      "pepino",
      "pimiento",
      "limón",
      "aceite de oliva",
    ],
    tiempo: "20 minutos",
    tipo: "Ensalada",
  },
  {
    id: 2,
    nombre: "Tacos de Coliflor",
    descripcion: "Tacos rellenos de coliflor al horno con especias.",
    pasos: ["Marina la coliflor", "Hornéala", "Arma los tacos"],
    dificultad: "Media",
    ingredientes: [
      "coliflor",
      "tortillas de maíz",
      "cebolla",
      "cilantro",
      "aguacate",
    ],
    tiempo: "30 minutos",
    tipo: "Tacos",
  },
  {
    id: 3,
    nombre: "Sopa de Calabaza",
    descripcion: "Sopa cremosa de calabaza con especias.",
    pasos: ["Corta la calabaza", "Cocina y tritura", "Sazona al gusto"],
    dificultad: "Media",
    ingredientes: ["calabaza", "cebolla", "ajo", "caldo de verduras", "crema"],
    tiempo: "40 minutos",
    tipo: "Sopa",
  },
  {
    id: 4,
    nombre: "Hamburguesa de Garbanzos",
    descripcion: "Hamburguesa hecha de garbanzos y especias.",
    pasos: ["Tritura los garbanzos", "Forma las hamburguesas", "Cocínalas"],
    dificultad: "Media",
    ingredientes: [
      "garbanzos",
      "cebolla",
      "ajo",
      "especias",
      "pan de hamburguesa",
    ],
    tiempo: "25 minutos",
    tipo: "Plato principal",
  },
  {
    id: 5,
    nombre: "Pasta al Pesto",
    descripcion: "Pasta con salsa pesto casera.",
    pasos: ["Cocina la pasta", "Prepara el pesto", "Mezcla y sirve"],
    dificultad: "Fácil",
    ingredientes: ["pasta", "albahaca", "piñones", "ajo", "aceite de oliva"],
    tiempo: "15 minutos",
    tipo: "Plato principal",
  },
  {
    id: 6,
    nombre: "Falafel",
    descripcion: "Croquetas de garbanzo fritas con especias.",
    pasos: ["Mezcla los ingredientes", "Forma croquetas", "Fríelas"],
    dificultad: "Media",
    ingredientes: ["garbanzos", "ajo", "cebolla", "especias", "aceite"],
    tiempo: "30 minutos",
    tipo: "Aperitivo",
  },
  {
    id: 7,
    nombre: "Wrap de Vegetales",
    descripcion: "Wrap con vegetales frescos y hummus.",
    pasos: ["Prepara el hummus", "Corta los vegetales", "Arma el wrap"],
    dificultad: "Fácil",
    ingredientes: ["tortilla", "hummus", "pepino", "lechuga", "zanahoria"],
    tiempo: "10 minutos",
    tipo: "Aperitivo",
  },
  {
    id: 8,
    nombre: "Curry de Verduras",
    descripcion: "Curry hecho con diversas verduras.",
    pasos: [
      "Corta y saltea las verduras",
      "Añade especias y leche de coco",
      "Cocina a fuego lento",
    ],
    dificultad: "Media",
    ingredientes: [
      "zanahoria",
      "pimiento",
      "calabacín",
      "leche de coco",
      "curry en polvo",
    ],
    tiempo: "45 minutos",
    tipo: "Plato principal",
  },
  {
    id: 9,
    nombre: "Pizza Vegetariana",
    descripcion: "Pizza con vegetales frescos.",
    pasos: ["Prepara la masa", "Añade salsa y vegetales", "Hornea"],
    dificultad: "Difícil",
    ingredientes: [
      "masa de pizza",
      "tomate",
      "pimiento",
      "cebolla",
      "aceitunas",
    ],
    tiempo: "50 minutos",
    tipo: "Plato principal",
  },
  {
    id: 10,
    nombre: "Berenjenas Rellenas",
    descripcion: "Berenjenas al horno rellenas de vegetales.",
    pasos: ["Vacía las berenjenas", "Rellénalas", "Hornéalas"],
    dificultad: "Media",
    ingredientes: [
      "berenjena",
      "tomate",
      "pimiento",
      "queso",
      "aceite de oliva",
    ],
    tiempo: "35 minutos",
    tipo: "Plato principal",
  },
];

export const recetasNoVegetarianas = [
  {
    id: 1,
    nombre: "Pollo al Horno",
    descripcion: "Pollo horneado con especias.",
    pasos: ["Marina el pollo", "Hornéalo a 180°C", "Sirve caliente"],
    dificultad: "Fácil",
    ingredientes: ["pollo", "ajo", "limón", "especias", "aceite de oliva"],
    tiempo: "60 minutos",
    tipo: "Plato principal",
  },
  {
    id: 2,
    nombre: "Tacos de Carne",
    descripcion: "Tacos de carne asada con vegetales.",
    pasos: ["Cocina la carne", "Corta los vegetales", "Arma los tacos"],
    dificultad: "Media",
    ingredientes: [
      "carne de res",
      "tortillas",
      "cebolla",
      "cilantro",
      "aguacate",
    ],
    tiempo: "20 minutos",
    tipo: "Tacos",
  },
  // Más recetas no vegetarianas
  {
    id: 3,
    nombre: "Sopa de Pollo",
    descripcion: "Sopa caliente con pollo y vegetales.",
    pasos: ["Cocina el pollo", "Agrega los vegetales", "Sazona al gusto"],
    dificultad: "Fácil",
    ingredientes: ["pollo", "zanahoria", "cebolla", "apio", "sal"],
    tiempo: "40 minutos",
    tipo: "Sopa",
  },
  {
    id: 4,
    nombre: "Lasaña de Carne",
    descripcion: "Lasaña con carne molida y queso.",
    pasos: ["Prepara la salsa", "Arma la lasaña", "Hornéala"],
    dificultad: "Difícil",
    ingredientes: [
      "carne molida",
      "salsa de tomate",
      "pasta de lasaña",
      "queso",
    ],
    tiempo: "60 minutos",
    tipo: "Plato principal",
  },
  {
    id: 5,
    nombre: "Ceviche de Camarones",
    descripcion: "Ceviche fresco con camarones marinados.",
    pasos: ["Marina los camarones", "Agrega vegetales y sazona", "Sirve frío"],
    dificultad: "Media",
    ingredientes: ["camarones", "limón", "cebolla", "pimiento", "cilantro"],
    tiempo: "25 minutos",
    tipo: "Aperitivo",
  },
  {
    id: 6,
    nombre: "Estofado de Res",
    descripcion: "Estofado de carne de res con vegetales.",
    pasos: ["Cocina la carne", "Añade los vegetales", "Cocina a fuego lento"],
    dificultad: "Media",
    ingredientes: [
      "carne de res",
      "zanahoria",
      "papas",
      "cebolla",
      "caldo de carne",
    ],
    tiempo: "90 minutos",
    tipo: "Plato principal",
  },
  {
    id: 7,
    nombre: "Costillas BBQ",
    descripcion: "Costillas de cerdo con salsa BBQ.",
    pasos: ["Marina las costillas", "Hornéalas", "Añade salsa BBQ"],
    dificultad: "Media",
    ingredientes: ["costillas de cerdo", "salsa BBQ", "especias", "miel"],
    tiempo: "120 minutos",
    tipo: "Plato principal",
  },
  {
    id: 8,
    nombre: "Arroz con Pollo",
    descripcion: "Arroz con pollo y vegetales.",
    pasos: [
      "Cocina el pollo",
      "Agrega el arroz y vegetales",
      "Cocina hasta que el arroz esté listo",
    ],
    dificultad: "Fácil",
    ingredientes: ["pollo", "arroz", "zanahoria", "cebolla", "caldo de pollo"],
    tiempo: "45 minutos",
    tipo: "Plato principal",
  },
  {
    id: 9,
    nombre: "Paella de Mariscos",
    descripcion: "Paella con mariscos frescos y arroz.",
    pasos: [
      "Saltea los mariscos",
      "Agrega el arroz y caldo",
      "Cocina a fuego lento",
    ],
    dificultad: "Difícil",
    ingredientes: [
      "mariscos variados",
      "arroz",
      "pimiento",
      "caldo de pescado",
      "azafrán",
    ],
    tiempo: "60 minutos",
    tipo: "Plato principal",
  },
  {
    id: 10,
    nombre: "Hamburguesa de Carne",
    descripcion: "Hamburguesa con carne y queso.",
    pasos: ["Forma las hamburguesas", "Cocínalas", "Arma la hamburguesa"],
    dificultad: "Fácil",
    ingredientes: [
      "carne molida",
      "pan de hamburguesa",
      "queso",
      "lechuga",
      "tomate",
    ],
    tiempo: "15 minutos",
    tipo: "Plato principal",
  },
];
